/**
 * Supabase Database Types - Auto-generated from schema.sql
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is generated by running:
 *   npm run db:types
 *
 * Which executes:
 *   npx supabase gen types typescript --project-id <project-ref> > src/types/generated.ts
 *
 * The CI workflow will fail if this file is out of sync with schema.sql.
 * After modifying schema.sql, regenerate this file and commit both together.
 *
 * @see https://supabase.com/docs/reference/cli/supabase-gen-types-typescript
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      ai_conversations: {
        Row: {
          course_id: number | null
          created_at: string | null
          id: string
          lesson_id: number | null
          model: string | null
          status: string | null
          title: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          course_id?: number | null
          created_at?: string | null
          id?: string
          lesson_id?: number | null
          model?: string | null
          status?: string | null
          title?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          course_id?: number | null
          created_at?: string | null
          id?: string
          lesson_id?: number | null
          model?: string | null
          status?: string | null
          title?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_conversations_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_conversations_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_messages: {
        Row: {
          content: string
          conversation_id: string | null
          cost: number | null
          created_at: string | null
          id: string
          metadata: Json | null
          role: string
          tokens_used: number | null
        }
        Insert: {
          content: string
          conversation_id?: string | null
          cost?: number | null
          created_at?: string | null
          id?: string
          metadata?: Json | null
          role: string
          tokens_used?: number | null
        }
        Update: {
          content?: string
          conversation_id?: string | null
          cost?: number | null
          created_at?: string | null
          id?: string
          metadata?: Json | null
          role?: string
          tokens_used?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "ai_conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_usage_logs: {
        Row: {
          cost: number
          created_at: string | null
          id: string
          metadata: Json | null
          model: string
          operation: string | null
          tokens_used: number
          user_id: string | null
        }
        Insert: {
          cost: number
          created_at?: string | null
          id?: string
          metadata?: Json | null
          model: string
          operation?: string | null
          tokens_used: number
          user_id?: string | null
        }
        Update: {
          cost?: number
          created_at?: string | null
          id?: string
          metadata?: Json | null
          model?: string
          operation?: string | null
          tokens_used?: number
          user_id?: string | null
        }
        Relationships: []
      }
      analytics_events: {
        Row: {
          created_at: string | null
          event_data: Json | null
          event_type: string
          id: string
          ip_address: unknown
          session_id: string | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          event_data?: Json | null
          event_type: string
          id?: string
          ip_address?: unknown
          session_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          event_data?: Json | null
          event_type?: string
          id?: string
          ip_address?: unknown
          session_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      announcements: {
        Row: {
          content: string
          created_at: string | null
          created_by: string | null
          expires_at: string | null
          id: string
          priority: string | null
          publish_at: string | null
          published: boolean | null
          scope: string
          target_id: string | null
          title: string
        }
        Insert: {
          content: string
          created_at?: string | null
          created_by?: string | null
          expires_at?: string | null
          id?: string
          priority?: string | null
          publish_at?: string | null
          published?: boolean | null
          scope: string
          target_id?: string | null
          title: string
        }
        Update: {
          content?: string
          created_at?: string | null
          created_by?: string | null
          expires_at?: string | null
          id?: string
          priority?: string | null
          publish_at?: string | null
          published?: boolean | null
          scope?: string
          target_id?: string | null
          title?: string
        }
        Relationships: []
      }
      applications: {
        Row: {
          assigned_reviewer_id: string | null
          assignment_date: string | null
          career_goals: string | null
          commitment: string | null
          created_at: string | null
          current_stage: string | null
          decision_note: string | null
          discord: string | null
          email: string
          funding: string | null
          id: string
          interests: string[] | null
          location: string | null
          motivation: string | null
          name: string
          production_needs: string | null
          program: string
          project_description: string | null
          project_name: string | null
          protected_class: string | null
          prototype_link: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          role: string | null
          scholarship_category: string | null
          scholarship_requested: boolean | null
          status: string
          target_users: string | null
          team_size: number | null
          tech_stack: string | null
          technical_experience: string | null
          track: string | null
          updated_at: string | null
          user_id: string | null
          whatsapp: string | null
        }
        Insert: {
          assigned_reviewer_id?: string | null
          assignment_date?: string | null
          career_goals?: string | null
          commitment?: string | null
          created_at?: string | null
          current_stage?: string | null
          decision_note?: string | null
          discord?: string | null
          email: string
          funding?: string | null
          id?: string
          interests?: string[] | null
          location?: string | null
          motivation?: string | null
          name: string
          production_needs?: string | null
          program: string
          project_description?: string | null
          project_name?: string | null
          protected_class?: string | null
          prototype_link?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          role?: string | null
          scholarship_category?: string | null
          scholarship_requested?: boolean | null
          status?: string
          target_users?: string | null
          team_size?: number | null
          tech_stack?: string | null
          technical_experience?: string | null
          track?: string | null
          updated_at?: string | null
          user_id?: string | null
          whatsapp?: string | null
        }
        Update: {
          assigned_reviewer_id?: string | null
          assignment_date?: string | null
          career_goals?: string | null
          commitment?: string | null
          created_at?: string | null
          current_stage?: string | null
          decision_note?: string | null
          discord?: string | null
          email?: string
          funding?: string | null
          id?: string
          interests?: string[] | null
          location?: string | null
          motivation?: string | null
          name?: string
          production_needs?: string | null
          program?: string
          project_description?: string | null
          project_name?: string | null
          protected_class?: string | null
          prototype_link?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          role?: string | null
          scholarship_category?: string | null
          scholarship_requested?: boolean | null
          status?: string
          target_users?: string | null
          team_size?: number | null
          tech_stack?: string | null
          technical_experience?: string | null
          track?: string | null
          updated_at?: string | null
          user_id?: string | null
          whatsapp?: string | null
        }
        Relationships: []
      }
      assignment_rubrics: {
        Row: {
          assignment_id: string | null
          created_at: string | null
          criterion: string
          description: string | null
          id: string
          max_points: number
          order_index: number
        }
        Insert: {
          assignment_id?: string | null
          created_at?: string | null
          criterion: string
          description?: string | null
          id?: string
          max_points: number
          order_index: number
        }
        Update: {
          assignment_id?: string | null
          created_at?: string | null
          criterion?: string
          description?: string | null
          id?: string
          max_points?: number
          order_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "assignment_rubrics_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "assignments"
            referencedColumns: ["id"]
          },
        ]
      }
      assignment_submissions: {
        Row: {
          assignment_id: string | null
          created_at: string | null
          feedback: string | null
          file_name: string | null
          file_size_bytes: number | null
          file_type: string | null
          file_url: string | null
          file_urls: string[] | null
          graded_at: string | null
          graded_by: string | null
          id: string
          is_late: boolean | null
          rubric_scores: Json | null
          score: number | null
          status: string | null
          submission_number: number | null
          submission_text: string | null
          submitted_at: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          assignment_id?: string | null
          created_at?: string | null
          feedback?: string | null
          file_name?: string | null
          file_size_bytes?: number | null
          file_type?: string | null
          file_url?: string | null
          file_urls?: string[] | null
          graded_at?: string | null
          graded_by?: string | null
          id?: string
          is_late?: boolean | null
          rubric_scores?: Json | null
          score?: number | null
          status?: string | null
          submission_number?: number | null
          submission_text?: string | null
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          assignment_id?: string | null
          created_at?: string | null
          feedback?: string | null
          file_name?: string | null
          file_size_bytes?: number | null
          file_type?: string | null
          file_url?: string | null
          file_urls?: string[] | null
          graded_at?: string | null
          graded_by?: string | null
          id?: string
          is_late?: boolean | null
          rubric_scores?: Json | null
          score?: number | null
          status?: string | null
          submission_number?: number | null
          submission_text?: string | null
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "assignment_submissions_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "assignments"
            referencedColumns: ["id"]
          },
        ]
      }
      assignments: {
        Row: {
          allow_late_submissions: boolean | null
          allow_resubmission: boolean | null
          allowed_file_types: string[] | null
          course_id: number | null
          created_at: string | null
          created_by: string | null
          description: string | null
          due_date: string | null
          id: string
          instructions: string | null
          is_published: boolean | null
          late_penalty_percent: number | null
          lesson_id: number | null
          max_file_size_mb: number | null
          max_points: number | null
          max_submissions: number | null
          module_id: number | null
          title: string
          updated_at: string | null
        }
        Insert: {
          allow_late_submissions?: boolean | null
          allow_resubmission?: boolean | null
          allowed_file_types?: string[] | null
          course_id?: number | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          instructions?: string | null
          is_published?: boolean | null
          late_penalty_percent?: number | null
          lesson_id?: number | null
          max_file_size_mb?: number | null
          max_points?: number | null
          max_submissions?: number | null
          module_id?: number | null
          title: string
          updated_at?: string | null
        }
        Update: {
          allow_late_submissions?: boolean | null
          allow_resubmission?: boolean | null
          allowed_file_types?: string[] | null
          course_id?: number | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          instructions?: string | null
          is_published?: boolean | null
          late_penalty_percent?: number | null
          lesson_id?: number | null
          max_file_size_mb?: number | null
          max_points?: number | null
          max_submissions?: number | null
          module_id?: number | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "assignments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assignments_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assignments_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      auth_logs: {
        Row: {
          created_at: string | null
          details: Json | null
          event_type: string
          id: string
          ip_address: unknown
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          details?: Json | null
          event_type: string
          id?: string
          ip_address?: unknown
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          details?: Json | null
          event_type?: string
          id?: string
          ip_address?: unknown
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      blog_posts: {
        Row: {
          author_id: string | null
          author_name: string | null
          category: string
          content: string
          created_at: string | null
          description: string | null
          featured_image: string | null
          id: string
          published_at: string | null
          slug: string
          status: string
          tags: string[] | null
          title: string
          updated_at: string | null
        }
        Insert: {
          author_id?: string | null
          author_name?: string | null
          category: string
          content?: string
          created_at?: string | null
          description?: string | null
          featured_image?: string | null
          id?: string
          published_at?: string | null
          slug: string
          status?: string
          tags?: string[] | null
          title: string
          updated_at?: string | null
        }
        Update: {
          author_id?: string | null
          author_name?: string | null
          category?: string
          content?: string
          created_at?: string | null
          description?: string | null
          featured_image?: string | null
          id?: string
          published_at?: string | null
          slug?: string
          status?: string
          tags?: string[] | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      certificate_templates: {
        Row: {
          created_at: string | null
          created_by: string | null
          description: string | null
          id: string
          is_default: boolean | null
          name: string
          template_html: string
          template_variables: string[] | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string
          is_default?: boolean | null
          name: string
          template_html: string
          template_variables?: string[] | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string
          is_default?: boolean | null
          name?: string
          template_html?: string
          template_variables?: string[] | null
          updated_at?: string | null
        }
        Relationships: []
      }
      certificates: {
        Row: {
          certificate_code: string
          completion_date: string | null
          course_id: number | null
          course_title: string
          created_at: string | null
          expiry_date: string | null
          final_grade: string | null
          id: string
          issued_date: string
          metadata: Json | null
          pdf_url: string | null
          student_name: string
          template_id: string | null
          user_id: string | null
        }
        Insert: {
          certificate_code: string
          completion_date?: string | null
          course_id?: number | null
          course_title: string
          created_at?: string | null
          expiry_date?: string | null
          final_grade?: string | null
          id?: string
          issued_date?: string
          metadata?: Json | null
          pdf_url?: string | null
          student_name: string
          template_id?: string | null
          user_id?: string | null
        }
        Update: {
          certificate_code?: string
          completion_date?: string | null
          course_id?: number | null
          course_title?: string
          created_at?: string | null
          expiry_date?: string | null
          final_grade?: string | null
          id?: string
          issued_date?: string
          metadata?: Json | null
          pdf_url?: string | null
          student_name?: string
          template_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "certificates_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "certificate_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      cohort_enrollments: {
        Row: {
          cohort_id: string | null
          completed_lessons: number | null
          enrolled_at: string | null
          id: string
          last_activity_at: string | null
          progress: Json | null
          status: string
          user_id: string | null
        }
        Insert: {
          cohort_id?: string | null
          completed_lessons?: number | null
          enrolled_at?: string | null
          id?: string
          last_activity_at?: string | null
          progress?: Json | null
          status?: string
          user_id?: string | null
        }
        Update: {
          cohort_id?: string | null
          completed_lessons?: number | null
          enrolled_at?: string | null
          id?: string
          last_activity_at?: string | null
          progress?: Json | null
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cohort_enrollments_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
        ]
      }
      cohort_schedules: {
        Row: {
          cohort_id: string | null
          created_at: string | null
          id: string
          lock_date: string | null
          module_id: number | null
          unlock_date: string
        }
        Insert: {
          cohort_id?: string | null
          created_at?: string | null
          id?: string
          lock_date?: string | null
          module_id?: number | null
          unlock_date: string
        }
        Update: {
          cohort_id?: string | null
          created_at?: string | null
          id?: string
          lock_date?: string | null
          module_id?: number | null
          unlock_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "cohort_schedules_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cohort_schedules_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      cohorts: {
        Row: {
          course_id: number | null
          created_at: string | null
          created_by: string | null
          end_date: string | null
          id: string
          max_students: number | null
          name: string
          start_date: string
          status: string
          updated_at: string | null
        }
        Insert: {
          course_id?: number | null
          created_at?: string | null
          created_by?: string | null
          end_date?: string | null
          id?: string
          max_students?: number | null
          name: string
          start_date: string
          status?: string
          updated_at?: string | null
        }
        Update: {
          course_id?: number | null
          created_at?: string | null
          created_by?: string | null
          end_date?: string | null
          id?: string
          max_students?: number | null
          name?: string
          start_date?: string
          status?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cohorts_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      course_forums: {
        Row: {
          cohort_id: string | null
          content: string
          course_id: number | null
          created_at: string | null
          id: string
          is_locked: boolean | null
          is_pinned: boolean | null
          title: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          cohort_id?: string | null
          content: string
          course_id?: number | null
          created_at?: string | null
          id?: string
          is_locked?: boolean | null
          is_pinned?: boolean | null
          title: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          cohort_id?: string | null
          content?: string
          course_id?: number | null
          created_at?: string | null
          id?: string
          is_locked?: boolean | null
          is_pinned?: boolean | null
          title?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "course_forums_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_forums_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          created_at: string | null
          created_by: string | null
          default_duration_weeks: number | null
          description: string | null
          difficulty: string | null
          enrollment_type: string | null
          id: number
          is_cohort_based: boolean | null
          is_published: boolean | null
          slug: string
          thumbnail_url: string | null
          title: string
          track: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          default_duration_weeks?: number | null
          description?: string | null
          difficulty?: string | null
          enrollment_type?: string | null
          id?: number
          is_cohort_based?: boolean | null
          is_published?: boolean | null
          slug: string
          thumbnail_url?: string | null
          title: string
          track?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          default_duration_weeks?: number | null
          description?: string | null
          difficulty?: string | null
          enrollment_type?: string | null
          id?: number
          is_cohort_based?: boolean | null
          is_published?: boolean | null
          slug?: string
          thumbnail_url?: string | null
          title?: string
          track?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      enrollments: {
        Row: {
          cohort_id: string | null
          completed_at: string | null
          course_id: number | null
          enrolled_at: string | null
          id: number
          progress_percentage: number | null
          status: string | null
          user_id: string | null
        }
        Insert: {
          cohort_id?: string | null
          completed_at?: string | null
          course_id?: number | null
          enrolled_at?: string | null
          id?: number
          progress_percentage?: number | null
          status?: string | null
          user_id?: string | null
        }
        Update: {
          cohort_id?: string | null
          completed_at?: string | null
          course_id?: number | null
          enrolled_at?: string | null
          id?: number
          progress_percentage?: number | null
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "enrollments_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      forum_replies: {
        Row: {
          content: string
          created_at: string | null
          forum_post_id: string | null
          id: string
          is_teacher_response: boolean | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          content: string
          created_at?: string | null
          forum_post_id?: string | null
          id?: string
          is_teacher_response?: boolean | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          content?: string
          created_at?: string | null
          forum_post_id?: string | null
          id?: string
          is_teacher_response?: boolean | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "forum_replies_forum_post_id_fkey"
            columns: ["forum_post_id"]
            isOneToOne: false
            referencedRelation: "course_forums"
            referencedColumns: ["id"]
          },
        ]
      }
      lesson_discussions: {
        Row: {
          cohort_id: string | null
          content: string
          created_at: string | null
          id: string
          is_pinned: boolean | null
          is_teacher_response: boolean | null
          lesson_id: number | null
          parent_id: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          cohort_id?: string | null
          content: string
          created_at?: string | null
          id?: string
          is_pinned?: boolean | null
          is_teacher_response?: boolean | null
          lesson_id?: number | null
          parent_id?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          cohort_id?: string | null
          content?: string
          created_at?: string | null
          id?: string
          is_pinned?: boolean | null
          is_teacher_response?: boolean | null
          lesson_id?: number | null
          parent_id?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lesson_discussions_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_discussions_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_discussions_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "lesson_discussions"
            referencedColumns: ["id"]
          },
        ]
      }
      lesson_progress: {
        Row: {
          cohort_id: string | null
          completed: boolean | null
          completed_at: string | null
          created_at: string | null
          id: number
          last_accessed_at: string | null
          lesson_id: number | null
          time_spent_seconds: number | null
          user_id: string | null
          video_position_seconds: number | null
          watch_count: number | null
        }
        Insert: {
          cohort_id?: string | null
          completed?: boolean | null
          completed_at?: string | null
          created_at?: string | null
          id?: number
          last_accessed_at?: string | null
          lesson_id?: number | null
          time_spent_seconds?: number | null
          user_id?: string | null
          video_position_seconds?: number | null
          watch_count?: number | null
        }
        Update: {
          cohort_id?: string | null
          completed?: boolean | null
          completed_at?: string | null
          created_at?: string | null
          id?: number
          last_accessed_at?: string | null
          lesson_id?: number | null
          time_spent_seconds?: number | null
          user_id?: string | null
          video_position_seconds?: number | null
          watch_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "lesson_progress_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_progress_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
        ]
      }
      lessons: {
        Row: {
          content: string | null
          created_at: string | null
          duration_minutes: number | null
          id: number
          is_preview: boolean | null
          module_id: number | null
          order_index: number
          resources: Json | null
          slug: string
          title: string
          updated_at: string | null
          video_url: string | null
          youtube_url: string | null
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          duration_minutes?: number | null
          id?: number
          is_preview?: boolean | null
          module_id?: number | null
          order_index: number
          resources?: Json | null
          slug: string
          title: string
          updated_at?: string | null
          video_url?: string | null
          youtube_url?: string | null
        }
        Update: {
          content?: string | null
          created_at?: string | null
          duration_minutes?: number | null
          id?: number
          is_preview?: boolean | null
          module_id?: number | null
          order_index?: number
          resources?: Json | null
          slug?: string
          title?: string
          updated_at?: string | null
          video_url?: string | null
          youtube_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lessons_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      media_library: {
        Row: {
          alt_text: string | null
          caption: string | null
          created_at: string | null
          file_name: string
          file_path: string
          file_size_bytes: number
          file_type: string
          folder: string | null
          id: string
          is_in_use: boolean | null
          is_public: boolean | null
          malware_scan_at: string | null
          malware_scan_status: string | null
          mime_type: string | null
          tags: string[] | null
          updated_at: string | null
          uploaded_by: string | null
          usage_count: number | null
        }
        Insert: {
          alt_text?: string | null
          caption?: string | null
          created_at?: string | null
          file_name: string
          file_path: string
          file_size_bytes: number
          file_type: string
          folder?: string | null
          id?: string
          is_in_use?: boolean | null
          is_public?: boolean | null
          malware_scan_at?: string | null
          malware_scan_status?: string | null
          mime_type?: string | null
          tags?: string[] | null
          updated_at?: string | null
          uploaded_by?: string | null
          usage_count?: number | null
        }
        Update: {
          alt_text?: string | null
          caption?: string | null
          created_at?: string | null
          file_name?: string
          file_path?: string
          file_size_bytes?: number
          file_type?: string
          folder?: string | null
          id?: string
          is_in_use?: boolean | null
          is_public?: boolean | null
          malware_scan_at?: string | null
          malware_scan_status?: string | null
          mime_type?: string | null
          tags?: string[] | null
          updated_at?: string | null
          uploaded_by?: string | null
          usage_count?: number | null
        }
        Relationships: []
      }
      message_threads: {
        Row: {
          created_at: string | null
          id: string
          last_message_at: string | null
          participant_ids: string[]
          subject: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          last_message_at?: string | null
          participant_ids: string[]
          subject?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          last_message_at?: string | null
          participant_ids?: string[]
          subject?: string | null
        }
        Relationships: []
      }
      messages: {
        Row: {
          attachments: string[] | null
          content: string
          created_at: string | null
          id: string
          read_by: string[] | null
          sender_id: string | null
          thread_id: string | null
        }
        Insert: {
          attachments?: string[] | null
          content: string
          created_at?: string | null
          id?: string
          read_by?: string[] | null
          sender_id?: string | null
          thread_id?: string | null
        }
        Update: {
          attachments?: string[] | null
          content?: string
          created_at?: string | null
          id?: string
          read_by?: string[] | null
          sender_id?: string | null
          thread_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "message_threads"
            referencedColumns: ["id"]
          },
        ]
      }
      modules: {
        Row: {
          course_id: number | null
          created_at: string | null
          description: string | null
          id: number
          order_index: number
          title: string
          updated_at: string | null
        }
        Insert: {
          course_id?: number | null
          created_at?: string | null
          description?: string | null
          id?: number
          order_index: number
          title: string
          updated_at?: string | null
        }
        Update: {
          course_id?: number | null
          created_at?: string | null
          description?: string | null
          id?: number
          order_index?: number
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "modules_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          content: string | null
          created_at: string | null
          id: string
          is_read: boolean | null
          link: string | null
          metadata: Json | null
          title: string
          type: string
          user_id: string | null
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          id?: string
          is_read?: boolean | null
          link?: string | null
          metadata?: Json | null
          title: string
          type: string
          user_id?: string | null
        }
        Update: {
          content?: string | null
          created_at?: string | null
          id?: string
          is_read?: boolean | null
          link?: string | null
          metadata?: Json | null
          title?: string
          type?: string
          user_id?: string | null
        }
        Relationships: []
      }
      payments: {
        Row: {
          amount: number
          course_id: number | null
          created_at: string | null
          currency: string | null
          description: string | null
          id: string
          metadata: Json | null
          paid_at: string | null
          payment_type: string | null
          status: string
          stripe_customer_id: string | null
          stripe_payment_id: string
          user_id: string | null
        }
        Insert: {
          amount: number
          course_id?: number | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          id?: string
          metadata?: Json | null
          paid_at?: string | null
          payment_type?: string | null
          status: string
          stripe_customer_id?: string | null
          stripe_payment_id: string
          user_id?: string | null
        }
        Update: {
          amount?: number
          course_id?: number | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          id?: string
          metadata?: Json | null
          paid_at?: string | null
          payment_type?: string | null
          status?: string
          stripe_customer_id?: string | null
          stripe_payment_id?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string | null
          display_name: string | null
          email: string | null
          full_name: string | null
          id: string
          preferences: Json | null
          role: string | null
          timezone: string | null
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          display_name?: string | null
          email?: string | null
          full_name?: string | null
          id: string
          preferences?: Json | null
          role?: string | null
          timezone?: string | null
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          display_name?: string | null
          email?: string | null
          full_name?: string | null
          id?: string
          preferences?: Json | null
          role?: string | null
          timezone?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      quiz_attempts: {
        Row: {
          answers_json: Json | null
          attempt_number: number
          cohort_id: string | null
          graded_at: string | null
          graded_by: string | null
          grading_status: string | null
          id: string
          passed: boolean | null
          points_earned: number | null
          quiz_id: string | null
          score: number | null
          started_at: string | null
          submitted_at: string | null
          time_taken_seconds: number | null
          total_points: number | null
          user_id: string | null
        }
        Insert: {
          answers_json?: Json | null
          attempt_number: number
          cohort_id?: string | null
          graded_at?: string | null
          graded_by?: string | null
          grading_status?: string | null
          id?: string
          passed?: boolean | null
          points_earned?: number | null
          quiz_id?: string | null
          score?: number | null
          started_at?: string | null
          submitted_at?: string | null
          time_taken_seconds?: number | null
          total_points?: number | null
          user_id?: string | null
        }
        Update: {
          answers_json?: Json | null
          attempt_number?: number
          cohort_id?: string | null
          graded_at?: string | null
          graded_by?: string | null
          grading_status?: string | null
          id?: string
          passed?: boolean | null
          points_earned?: number | null
          quiz_id?: string | null
          score?: number | null
          started_at?: string | null
          submitted_at?: string | null
          time_taken_seconds?: number | null
          total_points?: number | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quiz_attempts_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_attempts_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_questions: {
        Row: {
          answer_explanation: string | null
          correct_answer: string | null
          created_at: string | null
          id: string
          options: Json | null
          order_index: number
          points: number | null
          question_text: string
          question_type: string
          quiz_id: string | null
        }
        Insert: {
          answer_explanation?: string | null
          correct_answer?: string | null
          created_at?: string | null
          id?: string
          options?: Json | null
          order_index: number
          points?: number | null
          question_text: string
          question_type: string
          quiz_id?: string | null
        }
        Update: {
          answer_explanation?: string | null
          correct_answer?: string | null
          created_at?: string | null
          id?: string
          options?: Json | null
          order_index?: number
          points?: number | null
          question_text?: string
          question_type?: string
          quiz_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quiz_questions_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
        ]
      }
      quizzes: {
        Row: {
          available_from: string | null
          available_until: string | null
          course_id: number | null
          created_at: string | null
          created_by: string | null
          description: string | null
          id: string
          is_published: boolean | null
          lesson_id: number | null
          max_attempts: number | null
          module_id: number | null
          passing_score: number | null
          randomize_questions: boolean | null
          show_correct_answers: boolean | null
          show_results_immediately: boolean | null
          time_limit_minutes: number | null
          title: string
          updated_at: string | null
        }
        Insert: {
          available_from?: string | null
          available_until?: string | null
          course_id?: number | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string
          is_published?: boolean | null
          lesson_id?: number | null
          max_attempts?: number | null
          module_id?: number | null
          passing_score?: number | null
          randomize_questions?: boolean | null
          show_correct_answers?: boolean | null
          show_results_immediately?: boolean | null
          time_limit_minutes?: number | null
          title: string
          updated_at?: string | null
        }
        Update: {
          available_from?: string | null
          available_until?: string | null
          course_id?: number | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: string
          is_published?: boolean | null
          lesson_id?: number | null
          max_attempts?: number | null
          module_id?: number | null
          passing_score?: number | null
          randomize_questions?: boolean | null
          show_correct_answers?: boolean | null
          show_results_immediately?: boolean | null
          time_limit_minutes?: number | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quizzes_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quizzes_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quizzes_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean | null
          canceled_at: string | null
          created_at: string | null
          current_period_end: string
          current_period_start: string
          id: string
          plan: string
          status: string
          stripe_customer_id: string
          stripe_subscription_id: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          cancel_at_period_end?: boolean | null
          canceled_at?: string | null
          created_at?: string | null
          current_period_end: string
          current_period_start: string
          id?: string
          plan: string
          status: string
          stripe_customer_id: string
          stripe_subscription_id: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          cancel_at_period_end?: boolean | null
          canceled_at?: string | null
          created_at?: string | null
          current_period_end?: string
          current_period_start?: string
          id?: string
          plan?: string
          status?: string
          stripe_customer_id?: string
          stripe_subscription_id?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      student_roster_view: {
        Row: {
          cohort_id: string | null
          completed_lessons: number | null
          discussion_posts: number | null
          email: string | null
          enrolled_at: string | null
          forum_posts: number | null
          last_activity_at: string | null
          name: string | null
          status: string | null
          user_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cohort_enrollments_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      approve_application: {
        Args: { application_id: string }
        Returns: undefined
      }
      can_user_submit: {
        Args: { assignment_id_param: string; user_id_param: string }
        Returns: boolean
      }
      create_assignment_submission: {
        Args: {
          p_assignment_id: string
          p_file_name: string
          p_file_size_bytes: number
          p_file_type: string
          p_file_url: string
          p_user_id: string
        }
        Returns: {
          assignment_id: string | null
          created_at: string | null
          feedback: string | null
          file_name: string | null
          file_size_bytes: number | null
          file_type: string | null
          file_url: string | null
          file_urls: string[] | null
          graded_at: string | null
          graded_by: string | null
          id: string
          is_late: boolean | null
          rubric_scores: Json | null
          score: number | null
          status: string | null
          submission_number: number | null
          submission_text: string | null
          submitted_at: string | null
          updated_at: string | null
          user_id: string | null
        }
        SetofOptions: {
          from: "*"
          to: "assignment_submissions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      enroll_in_cohort: {
        Args: { p_cohort_id: string; p_user_id: string }
        Returns: {
          cohort_id: string | null
          completed_lessons: number | null
          enrolled_at: string | null
          id: string
          last_activity_at: string | null
          progress: Json | null
          status: string
          user_id: string | null
        }
        SetofOptions: {
          from: "*"
          to: "cohort_enrollments"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      generate_certificate_number: { Args: never; Returns: string }
      generate_verification_code: { Args: never; Returns: string }
      get_assignment_stats: {
        Args: { assignment_id_param: string }
        Returns: {
          average_score: number
          graded_submissions: number
          late_submissions: number
          on_time_submissions: number
          total_submissions: number
        }[]
      }
      get_course_completion_date: {
        Args: { check_course_id: number; check_user_id: string }
        Returns: string
      }
      get_user_role: { Args: { check_user_id: string }; Returns: string }
      is_admin:
        | { Args: never; Returns: boolean }
        | { Args: { user_uuid: string }; Returns: boolean }
      is_course_completed: {
        Args: { check_course_id: number; check_user_id: string }
        Returns: boolean
      }
      is_student_in_teacher_cohort: {
        Args: { student_id: string; teacher_id: string }
        Returns: boolean
      }
      is_teacher:
        | { Args: never; Returns: boolean }
        | { Args: { user_uuid: string }; Returns: boolean }
      refresh_student_roster_view: { Args: never; Returns: undefined }
      reject_application: {
        Args: { application_id: string }
        Returns: undefined
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      waitlist_application: {
        Args: { application_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// ============================================================================
// HELPER TYPES - Convenience aliases for common table types
// ============================================================================

// Authentication & User Management
/** Row type for applications table */
export type ApplicationRow = Database['public']['Tables']['applications']['Row'];
export type ApplicationInsert = Database['public']['Tables']['applications']['Insert'];
export type ApplicationUpdate = Database['public']['Tables']['applications']['Update'];

/** Row type for profiles table */
export type ProfileRow = Database['public']['Tables']['profiles']['Row'];
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert'];
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update'];

/** Row type for auth_logs table */
export type AuthLogRow = Database['public']['Tables']['auth_logs']['Row'];
export type AuthLogInsert = Database['public']['Tables']['auth_logs']['Insert'];
export type AuthLogUpdate = Database['public']['Tables']['auth_logs']['Update'];

// Course Structure
/** Row type for courses table */
export type CourseRow = Database['public']['Tables']['courses']['Row'];
export type CourseInsert = Database['public']['Tables']['courses']['Insert'];
export type CourseUpdate = Database['public']['Tables']['courses']['Update'];

/** Row type for modules table */
export type ModuleRow = Database['public']['Tables']['modules']['Row'];
export type ModuleInsert = Database['public']['Tables']['modules']['Insert'];
export type ModuleUpdate = Database['public']['Tables']['modules']['Update'];

/** Row type for lessons table */
export type LessonRow = Database['public']['Tables']['lessons']['Row'];
export type LessonInsert = Database['public']['Tables']['lessons']['Insert'];
export type LessonUpdate = Database['public']['Tables']['lessons']['Update'];

// Cohort System
/** Row type for cohorts table */
export type CohortRow = Database['public']['Tables']['cohorts']['Row'];
export type CohortInsert = Database['public']['Tables']['cohorts']['Insert'];
export type CohortUpdate = Database['public']['Tables']['cohorts']['Update'];

/** Row type for cohort_enrollments table */
export type CohortEnrollmentRow = Database['public']['Tables']['cohort_enrollments']['Row'];
export type CohortEnrollmentInsert = Database['public']['Tables']['cohort_enrollments']['Insert'];
export type CohortEnrollmentUpdate = Database['public']['Tables']['cohort_enrollments']['Update'];

/** Row type for cohort_schedules table */
export type CohortScheduleRow = Database['public']['Tables']['cohort_schedules']['Row'];
export type CohortScheduleInsert = Database['public']['Tables']['cohort_schedules']['Insert'];
export type CohortScheduleUpdate = Database['public']['Tables']['cohort_schedules']['Update'];

/** Row type for lesson_progress table */
export type LessonProgressRow = Database['public']['Tables']['lesson_progress']['Row'];
export type LessonProgressInsert = Database['public']['Tables']['lesson_progress']['Insert'];
export type LessonProgressUpdate = Database['public']['Tables']['lesson_progress']['Update'];

/** Row type for enrollments table */
export type EnrollmentRow = Database['public']['Tables']['enrollments']['Row'];
export type EnrollmentInsert = Database['public']['Tables']['enrollments']['Insert'];
export type EnrollmentUpdate = Database['public']['Tables']['enrollments']['Update'];

// Discussions & Forums
/** Row type for lesson_discussions table */
export type LessonDiscussionRow = Database['public']['Tables']['lesson_discussions']['Row'];
export type LessonDiscussionInsert = Database['public']['Tables']['lesson_discussions']['Insert'];
export type LessonDiscussionUpdate = Database['public']['Tables']['lesson_discussions']['Update'];

/** Row type for course_forums table */
export type CourseForumRow = Database['public']['Tables']['course_forums']['Row'];
export type CourseForumInsert = Database['public']['Tables']['course_forums']['Insert'];
export type CourseForumUpdate = Database['public']['Tables']['course_forums']['Update'];

/** Row type for forum_replies table */
export type ForumReplyRow = Database['public']['Tables']['forum_replies']['Row'];
export type ForumReplyInsert = Database['public']['Tables']['forum_replies']['Insert'];
export type ForumReplyUpdate = Database['public']['Tables']['forum_replies']['Update'];

// Quizzes
/** Row type for quizzes table */
export type QuizRow = Database['public']['Tables']['quizzes']['Row'];
export type QuizInsert = Database['public']['Tables']['quizzes']['Insert'];
export type QuizUpdate = Database['public']['Tables']['quizzes']['Update'];

/** Row type for quiz_questions table */
export type QuizQuestionRow = Database['public']['Tables']['quiz_questions']['Row'];
export type QuizQuestionInsert = Database['public']['Tables']['quiz_questions']['Insert'];
export type QuizQuestionUpdate = Database['public']['Tables']['quiz_questions']['Update'];

/** Row type for quiz_attempts table */
export type QuizAttemptRow = Database['public']['Tables']['quiz_attempts']['Row'];
export type QuizAttemptInsert = Database['public']['Tables']['quiz_attempts']['Insert'];
export type QuizAttemptUpdate = Database['public']['Tables']['quiz_attempts']['Update'];

// Assignments
/** Row type for assignments table */
export type AssignmentRow = Database['public']['Tables']['assignments']['Row'];
export type AssignmentInsert = Database['public']['Tables']['assignments']['Insert'];
export type AssignmentUpdate = Database['public']['Tables']['assignments']['Update'];

/** Row type for assignment_submissions table */
export type AssignmentSubmissionRow = Database['public']['Tables']['assignment_submissions']['Row'];
export type AssignmentSubmissionInsert = Database['public']['Tables']['assignment_submissions']['Insert'];
export type AssignmentSubmissionUpdate = Database['public']['Tables']['assignment_submissions']['Update'];

/** Row type for assignment_rubrics table */
export type AssignmentRubricRow = Database['public']['Tables']['assignment_rubrics']['Row'];
export type AssignmentRubricInsert = Database['public']['Tables']['assignment_rubrics']['Insert'];
export type AssignmentRubricUpdate = Database['public']['Tables']['assignment_rubrics']['Update'];

// Messaging & Notifications
/** Row type for message_threads table */
export type MessageThreadRow = Database['public']['Tables']['message_threads']['Row'];
export type MessageThreadInsert = Database['public']['Tables']['message_threads']['Insert'];
export type MessageThreadUpdate = Database['public']['Tables']['message_threads']['Update'];

/** Row type for messages table */
export type MessageRow = Database['public']['Tables']['messages']['Row'];
export type MessageInsert = Database['public']['Tables']['messages']['Insert'];
export type MessageUpdate = Database['public']['Tables']['messages']['Update'];

/** Row type for notifications table */
export type NotificationRow = Database['public']['Tables']['notifications']['Row'];
export type NotificationInsert = Database['public']['Tables']['notifications']['Insert'];
export type NotificationUpdate = Database['public']['Tables']['notifications']['Update'];

/** Row type for announcements table */
export type AnnouncementRow = Database['public']['Tables']['announcements']['Row'];
export type AnnouncementInsert = Database['public']['Tables']['announcements']['Insert'];
export type AnnouncementUpdate = Database['public']['Tables']['announcements']['Update'];

// AI Teaching Assistant
/** Row type for ai_conversations table */
export type AiConversationRow = Database['public']['Tables']['ai_conversations']['Row'];
export type AiConversationInsert = Database['public']['Tables']['ai_conversations']['Insert'];
export type AiConversationUpdate = Database['public']['Tables']['ai_conversations']['Update'];

/** Row type for ai_messages table */
export type AiMessageRow = Database['public']['Tables']['ai_messages']['Row'];
export type AiMessageInsert = Database['public']['Tables']['ai_messages']['Insert'];
export type AiMessageUpdate = Database['public']['Tables']['ai_messages']['Update'];

/** Row type for ai_usage_logs table */
export type AiUsageLogRow = Database['public']['Tables']['ai_usage_logs']['Row'];
export type AiUsageLogInsert = Database['public']['Tables']['ai_usage_logs']['Insert'];
export type AiUsageLogUpdate = Database['public']['Tables']['ai_usage_logs']['Update'];

// Certificates
/** Row type for certificate_templates table */
export type CertificateTemplateRow = Database['public']['Tables']['certificate_templates']['Row'];
export type CertificateTemplateInsert = Database['public']['Tables']['certificate_templates']['Insert'];
export type CertificateTemplateUpdate = Database['public']['Tables']['certificate_templates']['Update'];

/** Row type for certificates table */
export type CertificateRow = Database['public']['Tables']['certificates']['Row'];
export type CertificateInsert = Database['public']['Tables']['certificates']['Insert'];
export type CertificateUpdate = Database['public']['Tables']['certificates']['Update'];

// Payments
/** Row type for payments table */
export type PaymentRow = Database['public']['Tables']['payments']['Row'];
export type PaymentInsert = Database['public']['Tables']['payments']['Insert'];
export type PaymentUpdate = Database['public']['Tables']['payments']['Update'];

/** Row type for subscriptions table */
export type SubscriptionRow = Database['public']['Tables']['subscriptions']['Row'];
export type SubscriptionInsert = Database['public']['Tables']['subscriptions']['Insert'];
export type SubscriptionUpdate = Database['public']['Tables']['subscriptions']['Update'];

// Media Library
/** Row type for media_library table */
export type MediaLibraryRow = Database['public']['Tables']['media_library']['Row'];
export type MediaLibraryInsert = Database['public']['Tables']['media_library']['Insert'];
export type MediaLibraryUpdate = Database['public']['Tables']['media_library']['Update'];

// Analytics
/** Row type for analytics_events table */
export type AnalyticsEventRow = Database['public']['Tables']['analytics_events']['Row'];
export type AnalyticsEventInsert = Database['public']['Tables']['analytics_events']['Insert'];
export type AnalyticsEventUpdate = Database['public']['Tables']['analytics_events']['Update'];

// Blog
/** Row type for blog_posts table */
export type BlogPostRow = Database['public']['Tables']['blog_posts']['Row'];
export type BlogPostInsert = Database['public']['Tables']['blog_posts']['Insert'];
export type BlogPostUpdate = Database['public']['Tables']['blog_posts']['Update'];

// Views
/** Row type for student_roster_view materialized view */
export type StudentRosterViewRow = Database['public']['Views']['student_roster_view']['Row'];
